#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  case "$(uname -s)" in
    Linux)
      export DEBIAN_FRONTEND=noninteractive
      sudo -E apt-get install -y software-properties-common python-software-properties aptitude
      sudo env - add-apt-repository ppa:git-core/ppa
      sudo -E aptitude update -y && aptitude upgrade -y
      sudo -E aptitude install -y net-tools sudo cloud-init git openssh-server curl unzip perl ruby python language-pack-en build-essential vim man screen tmux
      sudo aptitude purge nano
      ;;
  esac
}

main "$@"
