#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  return 0

  if [[ ! -x "$shome/../fogg-cli/main" ]]; then
    return 1
  fi

  return 0
}

main "$@"
