#!/usr/bin/env bash

function _base_profile {
  local shome="${_base_home:="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"}"
  source "$shome/script/profile"

  if [[ -f /etc/lsb-release ]]; then
    . /etc/lsb-release
  fi

  : ${DISTRIB_ID:=}
  if [[ -z "${DISTRIB_ID}" ]]; then
    DISTRIB_ID="$(uname -s)"
  fi
}

_base_profile

