#!/usr/bin/env bash

function _base_profile {
  local shome="${_base_home:="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"}"

  PATH="$PATH:/sbin:/usr/sbin"

  : ${DISTRIB_ID:=}

  if [[ -f /etc/lsb-release ]]; then
    . /etc/lsb-release
  fi

  if [[ -z "${DISTRIB_ID}" ]]; then
    if [[ -f /etc/redhat-release ]]; then
      DISTRIB_ID="$(awk '{print $1}' /etc/redhat-release)"
    fi

  fi

  if [[ -z "${DISTRIB_ID}" ]]; then
    if [[ -f /etc/system-release ]]; then
      DISTRIB_ID="$(awk '{print $1}' /etc/system-release)"
    fi
  fi

  if [[ -z "${DISTRIB_ID}" ]]; then
    if [[ -f /etc/alpine-release ]]; then
      DISTRIB_ID="$(awk '{print $1}' /etc/system-release | cut -d. -f1-2)"
    fi
  fi

  if [[ -z "${DISTRIB_ID}" ]]; then
    DISTRIB_ID="$(uname -s)"
  fi

  export DISTRIB_ID
}

_base_profile

