#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  case "$DISTRIB_ID" in
    Amazon|CentOS)
      ${NOSUDO} sudo yum install -y gcc-c++ gcc diffutils # pkgsrc
      ${NOSUDO} sudo yum install -y zlib-devel # netdata
      ${NOSUDO} sudo yum install -y readline-devel # ruby
      ${NOSUDO} sudo yum install -y unzip nc # everyone
      ${NOSUDO} sudo yum install -y net-tools # openvpn
      ;;
  esac
}

main
